In [3]:
#tensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import datetime

#difference between tensorflow constant and tensorflow variable


In [4]:
#creating a trainable parameter
x=tf.Variable(2,trainable=True)

In [7]:
#basically finding dy/dx

x=tf.Variable(2.0,trainable=True)
with tf.GradientTape() as t:
  t.watch(x)
  y=x**2

print(t.gradient(y,x).numpy())

4.0


In [11]:
x=tf.Variable(2.0,trainable=True)
with tf.GradientTape() as t:
  t.watch(x)
  with tf.GradientTape() as tt:
    tt.watch(x)
    y=x**2
  first_derivative=tt.gradient(y,x)
second_derivative=t.gradient(first_derivative,x)
    
print(first_derivative.numpy())
print(second_derivative.numpy())

4.0
2.0


In [15]:
x=tf.Variable(2.0,trainable=True)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y=x**2
  z=y**2

print(t.gradient(z,x).numpy())
print(t.gradient(y,x).numpy())

32.0
4.0


In [22]:
x=tf.Variable(2.0,trainable=True)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y=x**3
  z=y**3

dz_dx_dy=t.gradient(z,[x,y])
print(dz_dx_dy)


[<tf.Tensor: shape=(), dtype=float32, numpy=32.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.0>]


In [27]:
x=tf.Variable(2.0,trainable=True)
y=tf.Variable(3.0,trainable=True)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  z=y**3 + x**3

dz_dx_dy=t.gradient(z,[x,y])

In [28]:
dz_dx_dy

[<tf.Tensor: shape=(), dtype=float32, numpy=12.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=27.0>]

In [31]:
x=tf.constant(2.0)
with tf.GradientTape() as t:
  t.watch(x)
  y=x**2

print(t.gradient(y,x).numpy())

4.0
